#!/usr/bin/env node
// Record what the PRODUCTION runtime's Math.exp / log / log1p return over the
// shared sweep, as digests: tests/fixtures/archbot/production-math.json.
//
// Must run on the production runtime (Node 22, x86-64, see pinned.mjs
// oracleCommand); it re-executes itself there when it is not already on it.
// tests/archbot-determinism.test.ts then requires ArchBot's determinism shim to
// reproduce these digests exactly, on whatever machine the test runs.
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { oracleCommand, repo } from "../pinned.mjs";
import { sweepBytes } from "./math-sweep.js";

const COUNT = 400_000;

if (process.env.ARCHBOT_MATH_GOLDEN_CHILD !== "1") {
  const { command, runtime } = oracleCommand();
  const run = spawnSync(command[0], [...command.slice(1), fileURLToPath(import.meta.url)], {
    env: { ...process.env, ARCHBOT_MATH_GOLDEN_CHILD: "1" },
    stdio: ["ignore", "pipe", "inherit"],
  });
  if (run.status !== 0) process.exit(run.status ?? 1);
  const digests = JSON.parse(run.stdout.toString());
  const out = join(repo, "tests/fixtures/archbot/production-math.json");
  writeFileSync(
    out,
    `${JSON.stringify({ comment: "Generated by tools/archbot/parity/math-golden.mjs on the production runtime.", runtime, count: COUNT, digests }, null, 1)}\n`,
  );
  console.log(`wrote ${out.slice(repo.length + 1)} from ${JSON.stringify(runtime)}`);
} else {
  const digests = {};
  for (const fn of ["exp", "log", "log1p"]) {
    digests[fn] = createHash("sha256")
      .update(sweepBytes(fn, Math[fn], COUNT))
      .digest("hex");
  }
  process.stdout.write(JSON.stringify(digests));
}
