import {
  makeSnapshot,
  restoreSnapshot,
  type GameState,
  type NewGameSettings,
  type Side,
  type TurnLog,
} from "../game";
import { settingsFromWaitingGame, startWaitingGame, updateWaitingGame } from "../pregame";
import { settleNormalClock } from "../features/ranked/rules";
import {
  continueFrom,
  pruneLine,
  type ContinueTarget,
  type Multiverse,
} from "../gameplay/multiverse";
import type { LiveAuthorityFacts, LiveCapabilities } from "./capabilities";

export type WaitingConfiguration = Pick<
  NewGameSettings,
  | "name"
  | "playerA"
  | "playerB"
  | "playerAUserId"
  | "playerBUserId"
  | "startingSide"
  | "timerMinutes"
>;
export type LiveControl =
  | { kind: "configure"; settings: WaitingConfiguration }
  | { kind: "ready"; ready: boolean }
  | { kind: "launch" }
  | { kind: "start" }
  | { kind: "rename"; name: string }
  | { kind: "request-pause" }
  | { kind: "respond-pause"; requestId: string; accept: boolean; blockFiveMinutes?: boolean }
  | { kind: "acknowledge-pause"; responseId: string }
  | { kind: "resume-direct" }
  | { kind: "save-exit" }
  | { kind: "undo" }
  | { kind: "redo" }
  | { kind: "annotate"; logId: string; note: string; stars: number }
  | { kind: "continue"; target: ContinueTarget }
  | { kind: "prune"; lineId: string };

const waitingKinds = new Set(["configure", "ready", "launch", "start"]);
const pauseKinds = new Set([
  "request-pause",
  "respond-pause",
  "acknowledge-pause",
  "resume-direct",
]);
export function canControlLive(
  facts: LiveAuthorityFacts,
  game: GameState,
  caps: LiveCapabilities,
  actor: string,
  kind: string,
): boolean {
  if (game.status === "finished" || facts.authorityProtocol !== "server-v1") return false;
  if (waitingKinds.has(kind))
    return game.roomStage === "waiting" && (kind === "ready" ? Boolean(caps.side) : caps.configure);
  if (game.roomStage === "waiting") return false;
  if (kind === "rename") return actor === facts.ownerId;
  if (kind === "save-exit") return caps.administer && !game.emailPlayMode;
  if (pauseKinds.has(kind))
    return game.emailPlayMode === "direct" && !game.botSide && Boolean(caps.side);
  return ["undo", "redo", "annotate", "continue", "prune"].includes(kind) && caps.editHistory;
}

export function requiredReadySides(facts: LiveAuthorityFacts, game: GameState): Side[] {
  return (["A", "B"] as Side[]).filter(
    (side) =>
      !(game.gameMode === "solo" && side === "B") &&
      side !== game.botSide &&
      Boolean(facts.seats[side]) &&
      facts.seats[side] !== facts.ownerId,
  );
}
export function launchReady(facts: LiveAuthorityFacts, game: GameState): boolean {
  const filled =
    facts.mode === "local_versus" ||
    game.gameMode === "solo" ||
    game.botSide ||
    (facts.seats.A && facts.seats.B);
  return Boolean(
    filled && requiredReadySides(facts, game).every((side) => game.lobbyReadyBySide?.[side]),
  );
}
function validName(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0 && value.length <= 160;
}

/** Input contains public decisions and private-history references only. Canonical
 * reconstruction stays here, behind authenticated stored capabilities. */
export function applyLiveControl(
  game: GameState,
  timeline: Multiverse,
  facts: LiveAuthorityFacts,
  caps: LiveCapabilities,
  action: LiveControl,
  now: string,
): { game: GameState; timeline?: Multiverse } {
  if (action.kind === "configure") {
    const settings = action.settings;
    if (
      !settings ||
      Object.keys(settings).some(
        (key) =>
          ![
            "name",
            "playerA",
            "playerB",
            "playerAUserId",
            "playerBUserId",
            "startingSide",
            "timerMinutes",
          ].includes(key),
      ) ||
      !validName(settings.name) ||
      !validName(settings.playerA) ||
      !(game.gameMode === "solo"
        ? typeof settings.playerB === "string" && settings.playerB.length <= 160
        : validName(settings.playerB)) ||
      !["A", "B"].includes(settings.startingSide ?? "") ||
      !settings.timerMinutes ||
      ["A", "B"].some((side) => {
        const minutes = settings.timerMinutes![side as Side];
        return minutes !== null && (!Number.isInteger(minutes) || minutes < 1 || minutes > 1440);
      })
    )
      throw new Error("Invalid waiting settings");
    // Bot/catalog/mode/funding and policy are immutable here. A fresh deal is
    // generated by the authority, never accepted from the submitted settings.
    if (game.botSide || facts.mode === "local_versus") {
      if (
        (settings.playerAUserId ?? null) !== (facts.seats.A ?? null) ||
        (settings.playerBUserId ?? null) !== (facts.seats.B ?? null)
      )
        throw new Error("Fixed seats");
    }
    const next = updateWaitingGame(game, {
      ...settingsFromWaitingGame(game),
      name: settings.name,
      playerA: settings.playerA,
      playerB: settings.playerB,
      playerAUserId: settings.playerAUserId,
      playerBUserId: settings.playerBUserId,
      startingSide: settings.startingSide,
      timerMinutes: { A: settings.timerMinutes.A, B: settings.timerMinutes.B },
      playerAEmail: null,
      playerBEmail: null,
    });
    return {
      game: {
        ...next,
        emailPlayMode: game.emailPlayMode,
        currentTurnStartedAt: now,
        lastSavedAt: now,
      },
    };
  }
  if (action.kind === "ready") {
    if (typeof action.ready !== "boolean" || !caps.side) throw new Error("Invalid Ready");
    return {
      game: {
        ...game,
        lobbyReadyBySide: { ...game.lobbyReadyBySide, [caps.side]: action.ready },
        lobbyLaunchAt: action.ready ? game.lobbyLaunchAt : undefined,
        lastSavedAt: now,
      },
    };
  }
  if (action.kind === "launch" || action.kind === "start") {
    if (!launchReady(facts, game)) throw new Error("Players are not ready");
    if (action.kind === "launch")
      return {
        game: {
          ...game,
          lobbyLaunchAt: game.lobbyLaunchAt ?? new Date(Date.parse(now) + 3000).toISOString(),
          lastSavedAt: now,
        },
      };
    if (!game.lobbyLaunchAt || Date.parse(now) < Date.parse(game.lobbyLaunchAt))
      throw new Error("Countdown pending");
    return { game: { ...startWaitingGame(game), currentTurnStartedAt: now, lastSavedAt: now } };
  }
  if (action.kind === "rename") {
    if (!validName(action.name)) throw new Error("Invalid name");
    return { game: { ...game, name: action.name.trim(), lastSavedAt: now } };
  }
  if (
    ["request-pause", "respond-pause", "acknowledge-pause", "resume-direct"].includes(action.kind)
  ) {
    const side = caps.side!;
    const control = { ...game.matchControl };
    let next = settleNormalClock(game, now);
    if (action.kind === "request-pause") {
      if (
        game.status !== "playing" ||
        control.stopRequest ||
        Date.parse(control.stopBlockedUntilBySide?.[side] ?? "") > Date.parse(now)
      )
        throw new Error("Pause request unavailable");
      control.stopRequest = { id: crypto.randomUUID(), requestedBy: side, requestedAt: now };
      control.stopResponse = undefined;
    } else if (action.kind === "respond-pause") {
      const request = control.stopRequest;
      if (
        !request ||
        request.id !== action.requestId ||
        request.requestedBy === side ||
        typeof action.accept !== "boolean" ||
        game.status !== "playing"
      )
        throw new Error("Invalid pause response");
      control.stopResponse = {
        id: crypto.randomUUID(),
        requestId: request.id,
        requestedBy: request.requestedBy,
        respondedBy: side,
        accepted: action.accept,
        respondedAt: now,
        ...(action.blockFiveMinutes && !action.accept ? { blockedForMs: 300000 } : {}),
      };
      control.stopRequest = undefined;
      if (action.accept) {
        control.stoppedBy = side;
        next = { ...next, status: "draft", timers: { ...next.timers, paused: true } };
      } else if (action.blockFiveMinutes)
        control.stopBlockedUntilBySide = {
          ...control.stopBlockedUntilBySide,
          [request.requestedBy]: new Date(Date.parse(now) + 300000).toISOString(),
        };
    } else if (action.kind === "acknowledge-pause") {
      if (
        !control.stopResponse ||
        control.stopResponse.id !== action.responseId ||
        control.stopResponse.requestedBy !== side
      )
        throw new Error("Invalid acknowledgement");
      control.stopResponse = undefined;
    } else {
      if (game.status !== "draft") throw new Error("Game is not paused");
      control.stoppedBy = undefined;
      next = { ...next, status: "playing", timers: { ...next.timers, paused: false } };
    }
    return {
      game: { ...next, matchControl: control, currentTurnStartedAt: now, lastSavedAt: now },
    };
  }
  if (action.kind === "save-exit") {
    const next = settleNormalClock(game, now);
    return {
      game: {
        ...next,
        status: "draft",
        timers: { ...next.timers, paused: true },
        currentTurnStartedAt: now,
        lastSavedAt: now,
      },
    };
  }
  if (action.kind === "undo" || action.kind === "redo") {
    const index = game.historyIndex + (action.kind === "undo" ? -1 : 1);
    if (
      index < 0 ||
      index >= game.history.length ||
      game.history[index].status === "finished" ||
      game.history[index].roomStage === "waiting"
    )
      throw new Error("History boundary");
    const restored = restoreSnapshot(game, index),
      settled = settleNormalClock(game, now);
    // Restore the private POSITION. Identity, lifecycle, live clocks and current
    // timeline stay with the room, as in the original committed undo behavior.
    return {
      game: {
        ...game,
        board: restored.board,
        rackA: restored.rackA,
        rackB: restored.rackB,
        tilebag: restored.tilebag,
        pendingExchangeReturn: restored.pendingExchangeReturn,
        pendingExchangeReturnBySide: restored.pendingExchangeReturnBySide,
        faceDownCount: restored.faceDownCount,
        scores: restored.scores,
        turnNumber: restored.turnNumber,
        activeSide: restored.activeSide,
        phase: restored.phase,
        logs: restored.logs,
        historyIndex: index,
        timers: settled.timers,
        currentTurnStartedAt: now,
        lastSavedAt: now,
      },
    };
  }
  if (action.kind === "annotate") {
    if (
      typeof action.logId !== "string" ||
      typeof action.note !== "string" ||
      action.note.length > 4000 ||
      !Number.isInteger(action.stars) ||
      action.stars < 0 ||
      action.stars > 5 ||
      ![...game.logs, ...timeline.lines.flatMap((line) => line.logs)].some(
        (log) => log.id === action.logId,
      )
    )
      throw new Error("Invalid annotation");
    const apply = (log: TurnLog): TurnLog =>
      log.id === action.logId ? { ...log, note: action.note, stars: action.stars } : log;
    const changed = timeline.lines.some((line) => line.logs.some((log) => log.id === action.logId));
    const branches = changed
      ? {
          version: timeline.version + 1,
          lines: timeline.lines.map((line) => ({ ...line, logs: line.logs.map(apply) })),
        }
      : undefined;
    return {
      game: {
        ...game,
        logs: game.logs.map(apply),
        history: game.history.map((snapshot) => ({ ...snapshot, logs: snapshot.logs.map(apply) })),
        ...(branches
          ? { timelineRef: { version: branches.version, lines: branches.lines.length } }
          : {}),
        lastSavedAt: now,
      },
      timeline: branches,
    };
  }
  if (action.kind === "continue") {
    if (
      !action.target ||
      !["before", "after"].includes(action.target.phase) ||
      (action.target.nodeId !== null && typeof action.target.nodeId !== "string")
    )
      throw new Error("Invalid history reference");
    const result = continueFrom(game, timeline, action.target, { now });
    if (!result.ok) throw new Error("Position unavailable");
    return { game: result.game, ...(result.changed ? { timeline: result.multiverse } : {}) };
  }
  if (action.kind === "prune") {
    if (!timeline.lines.some((line) => line.id === action.lineId))
      throw new Error("Unknown parked line");
    const branches = pruneLine(timeline, action.lineId);
    return {
      game: {
        ...game,
        timelineRef: { version: branches.version, lines: branches.lines.length },
        lastSavedAt: now,
      },
      timeline: branches,
    };
  }
  throw new Error("Invalid control");
}

export function ensureHistory(game: GameState): GameState {
  return game.history.length ? game : { ...game, history: [makeSnapshot(game)], historyIndex: 0 };
}
